name: Laravel CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Execute tests (Unit and Feature tests)
        run: php artisan test
      - name: Execute tests (Browser test with dusk)
        run: |
          php artisan dusk:chrome-driver
          php artisan dusk:serve
